// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALbWhBvwtVG3QzWIWh3WbB4irIb1aOc-g',
    appId: '1:890324288972:web:576390d1092cae9cbb8969',
    messagingSenderId: '890324288972',
    projectId: 'flutter-firebase-profile-auth',
    authDomain: 'flutter-firebase-profile-auth.firebaseapp.com',
    storageBucket: 'flutter-firebase-profile-auth.appspot.com',
    measurementId: 'G-W9QZ0HPZYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw1Pjns8Z0XQeiAfuVlCBfXmxgv1cumBw',
    appId: '1:890324288972:android:6fae20728ed561c6bb8969',
    messagingSenderId: '890324288972',
    projectId: 'flutter-firebase-profile-auth',
    storageBucket: 'flutter-firebase-profile-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJJYoX72VWpqFW-Ih88i3v-N9sme7AXI',
    appId: '1:890324288972:ios:7f227795e695f55ebb8969',
    messagingSenderId: '890324288972',
    projectId: 'flutter-firebase-profile-auth',
    storageBucket: 'flutter-firebase-profile-auth.appspot.com',
    iosBundleId: 'com.example.profileAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJJYoX72VWpqFW-Ih88i3v-N9sme7AXI',
    appId: '1:890324288972:ios:7f227795e695f55ebb8969',
    messagingSenderId: '890324288972',
    projectId: 'flutter-firebase-profile-auth',
    storageBucket: 'flutter-firebase-profile-auth.appspot.com',
    iosBundleId: 'com.example.profileAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALbWhBvwtVG3QzWIWh3WbB4irIb1aOc-g',
    appId: '1:890324288972:web:6e8ea9b41be1339cbb8969',
    messagingSenderId: '890324288972',
    projectId: 'flutter-firebase-profile-auth',
    authDomain: 'flutter-firebase-profile-auth.firebaseapp.com',
    storageBucket: 'flutter-firebase-profile-auth.appspot.com',
    measurementId: 'G-9WKXCZG73L',
  );
}
